### ISSUE TITLE
server process uses 100% of a cpu core

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-intellij-plugin#2]
On IJ2014 (i have an ultimate license for that version), the Kobalt plugin starts a server process that uses up 100% of a cpu core.

<img width="1178" alt="screen shot 2016-01-11 at 1 38 45 am" src="https://cloud.githubusercontent.com/assets/10501896/12228668/59856586-b804-11e5-9877-770acb4b6648.png">

**Comment by pabl0rg** [comment]
I tried the same project on IJ 2015 CE and have had no problems so far.

**Comment by cbeust** [comment]
I have observed such processes occasionally as well, I'll take a look.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
@pabl0rg Still valid for you? Didn't saw such CPU consuming.....

**Comment by pabl0rg** [comment]
@dmitry-zhuravlev I haven't had this problem in weeks. So it seems fixed to me.

**Comment by dmitry-zhuravlev** [comment]
Thanks for feedback!
