### ISSUE TITLE
Enhance TaskData with task group information

### ISSUE THREAD

**Issue by dmitry-zhuravlev** [cbeust/kobalt-intellij-plugin#23]
Current task data returned from server is 
`class TaskData(val name: String, val description: String)`
Nullable task group field should be added:
`class TaskData(val name: String, val description: String, val taskGroup: String?)`

Kobalt server should provide task group information.
This information will be used in Kobalt tool window. All tasks will be rearranged by its group. If no group specified the task will be added to "other" group.
See the Gradle task groups like an example:
![image](https://cloud.githubusercontent.com/assets/6297697/15074844/f45e7b8c-13a9-11e6-8dfd-6ac9d8b14145.png)

**Comment by cbeust** [comment]
Yup, will take care of it.

**Comment by cbeust** [comment]
Groups are now being sent from the server, I defined a few, let me know if we need more.
