### ISSUE TITLE
plugin does not add file dependencies to project structure

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-intellij-plugin#24]
all of my maven dependencies get added but compile(file("x:y:z")) dependencies do not get added to the project structure which leads to red in many places

**Comment by dmitry-zhuravlev** [comment]
Could you please attach a sample project to reproduce?
Also which version of plugin do you use?

**Comment by pabl0rg** [comment]
done
https://github.com/pabl0rg/kobalt-mixed-example

after syncing the build file, these are the dependencies added to the project structure (jrobin is missing)
<img width="680" alt="screen shot 2016-05-06 at 10 51 30 am" src="https://cloud.githubusercontent.com/assets/10501896/15079920/9c5a7e9e-1378-11e6-80b4-48a11598e430.png">

**Comment by cbeust** [comment]
I know what's going on. Until I fix it, the workaround is to specify an absolute path:

```
        compile(file(homeDir("YOUR_PROJECT_PATH/lib/jrobin-1.5.9.jar")))
```

**Comment by cbeust** [comment]
Uploaded a new version of the plug-in to the channel.
