### ISSUE TITLE
Handle bad build files better

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#25]
If there is a syntax error in the build file, syncing produces an unhelpful error message.

This requires some tweaking on both kobalt and the plug-in, but I'll take care of both.

**Comment by dmitry-zhuravlev** [comment]
Should be already done:
![untitled](https://cloud.githubusercontent.com/assets/6297697/24462260/35a69e36-14ac-11e7-9a9d-631885b25146.png)
