### ISSUE TITLE
dependent projects in same path generate incorrect modules in IJ

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-intellij-plugin#3]
I have a mixed java/kotlin project.  In order to build it with Kobalt, I have to define it as two projects.  When I sync the build file with the intellij plugin, it modifies my project structure adding modules for the two projects.  Since the two projects are in the same folder, i end up with two modules that have the same source root which IJ does not allow.

<img width="409" alt="screen shot 2016-01-13 at 2 14 24 am" src="https://cloud.githubusercontent.com/assets/10501896/12288695/0e8ee432-b99c-11e5-90ba-fb583cde50d8.png">

I think the ideal solution would be to have a mixed project type.

Thanks!

**Comment by pabl0rg** [comment]
PS. My build file is in /Users/juanliska/Documents/startrack/code/backend-2/kobalt/src/Build.kt

A better content root would be /Users/juanliska/Documents/startrack/code/backend-2/

**Comment by pabl0rg** [comment]
fixed in .404

**Comment by cbeust** [comment]
I'm surprised to hear that, I can't think of anything I added in the latest
versions that could have fixed this.

## 

Cédric

**Comment by pabl0rg** [comment]
Doh, i closed the wrong ticket.

**Comment by dmitry-zhuravlev** [comment]
@pabl0rg Can you please recheck if this issue still valid for you?

**Comment by pabl0rg** [comment]
Kobalt now supports mixed java + kotlin projects, so it no longer requires that i define two projects for the same source root.

However, I tested it out [here](https://github.com/pabl0rg/kobalt-mixed-example) and IJ threw no errors and created the project like this:

<img width="238" alt="screen shot 2017-04-06 at 12 52 24 pm" src="https://cloud.githubusercontent.com/assets/10501896/24770648/ed1ec234-1ac7-11e7-8b91-06f74c3ccda1.png">
