### ISSUE TITLE
Help reviewing steps to IJ plugin success

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-intellij-plugin#30]
I tried using the new kobalt IJ plugin to make a kobalt project and was unable to.  I usually use the cli for kobalt, and find it is simple to use.  

So I'm trying to make a gist to nail down the steps to get a kobalt project working, but I'm stuck in the last part (getting the IJ plugin to show me the sync build file option).  

Could you please review these steps and tell me where i'm going wrong?  https://gist.github.com/pabl0rg/f788a1ed0c3a4f43efdf17aed244b473

Thank you

**Comment by dmitry-zhuravlev** [comment]
Hi @pabl0rg
Please se my comments here https://github.com/cbeust/kobalt/issues/201

**Comment by pabl0rg** [comment]
Hi @dmitry-zhuravlev 

That is an interesting thread, thanks.  We usually compile and test from the command line and I noticed that when I make a new project with the IJ Kobalt plugin, kobaltw and kobalt-wrapper.properties are not recorded in the project folder, so our usual compilation does not work (running ./kobalw assemble for instance).

Are we doing something wrong?  Is there a better way?

Thank you

**Comment by dmitry-zhuravlev** [comment]
Hi @pabl0rg,
You noticed right. Plugin works without wrapper. There is no need to create this additional wrapper process when plugin works. However I understand that wrapper is a good way if you works from command line. @cbeust So I think we need some extra Kobalt task to init wrapper like Gradle have.

**Comment by pabl0rg** [comment]
I'm still having some trouble bridging the cli and IDE worlds.

Following the steps from the gist above, i got this error just now with kobalt 0.798 and IJ plugin 1.109

When i click on show log, nothing happens :-/

<img width="966" alt="screen shot 2016-06-01 at 10 59 39 am" src="https://cloud.githubusercontent.com/assets/10501896/15718370/4805c504-27e8-11e6-9f52-a692cd0786fd.png">

**Comment by cbeust** [comment]
@pabl0rg Yes, @dmitry-zhuravlev identified this issue as a difference between the way he and I build and package the plug-in. We're currently discussing the solution.

**Comment by cbeust** [comment]
FYI, here is where the discussion is taking place:

https://github.com/cbeust/kobalt-intellij-plugin/issues/33

**Comment by pabl0rg** [comment]
@cbeust @dmitry-zhuravlev  Ok!  it would be cool if when a project is created the source and test source folders were automatically set as such.  Sorry i haven't been much help in implementing much.  I'm buried in work.

**Comment by cbeust** [comment]
@pabl0rg Can you file a separate issue for the test directories?

Thanks!

**Comment by pabl0rg** [comment]
I'm closing this as the [steps in this gist](https://gist.github.com/pabl0rg/f788a1ed0c3a4f43efdf17aed244b473) now work well for me every time.  However, it's still a lot of steps.

If the IJ plugin were to install the wrapper in the project root, then we could eliminate all those steps and just tell people to install the plugin.

**Comment by cbeust** [comment]
@dmitry-zhuravlev Do you think we can improve on these steps, as @pabl0rg suggests?

**Comment by dmitry-zhuravlev** [comment]
I think that wrapper and this steps is a quite different things. Usually if the user works from IDEA then wrapper doesn't needed. Thats why in Gradle there is an option before import if user wants to install a wrapper or not. The wrapper usually neded when the user wants to share project with other colegues or he wants to build the project outside the IDEA. So we can just add the ability to user to decide if he wants wrapper in project.

Also I think we should describe steps how to work with plugin without CLI- it is more simple to use and plugin already can eliminate all steps which you mentioned in gist.

**Comment by dmitry-zhuravlev** [comment]
The simpliest way to add ability to add wrapper is the general Kobalt task "generateWrapper". 

The second way and more complex is to add additional checkbox in import window (like in Gradle plugin).

Actually the both way could be combined and let the user deceide which approach he want to use.

**Comment by pabl0rg** [comment]
The advantage of a generateWrapper or installWrapper task is that it can be
run at any time
