### ISSUE TITLE
Can't refresh a new project from the wizard

### ISSUE THREAD

**Issue by yoavst** [cbeust/kobalt-intellij-plugin#32]
Create a regular project (kotlin + java) from the wizard, and tried to sync the project:
`Error:com.intellij.execution.configurations.SimpleJavaParameters.toCommandLine()Lcom/intellij/execution/configurations/GeneralCommandLine;`

If trying to set to another kobalt jar directory, it says:
`Error:Illegal char <:> at index 45: C:\Users\yoavst\.kobalt/wrapper/dist/kobalt-C:/My Program Files/kobalt/kobalt/kobalt/wrapper/kobalt-C:/My Program Files/kobalt/kobalt.jar`

**Comment by dmitry-zhuravlev** [comment]
Duplication of #33
