### ISSUE TITLE
New project "Next" button does nothing

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#35]
From the IntelliJ welcome screen, I select "Create new project". I then select Kobalt and check Kotlin, and click next. The next button does nothing. The log shows a NullPointerException every time I click the button:

http://pastebin.com/raw/b9RqWVY1

Another related stack trace:

http://pastebin.com/raw/hh6zKSfn

Making the folder structure manually (or copying from another project) and using the import wizard seems to work fine, it's just the new project wizard that's causing the problem.

**Comment by sargunv** [comment]
Actually, it seems to not be changing the pane on the right at all when I select the Kobalt option. It remains the same as whatever pane was open before it.

**Comment by cbeust** [comment]
Haven't seen that one. @dmitry-zhuravlev, any thoughts?

**Comment by dmitry-zhuravlev** [comment]
I was able to reproduce this problem only when I install the plugin from JB repository. If Itry to build it from source and install from the disk it works.
Here is my distribution which I have build:
[kobalt-intellij-plugin.zip](https://github.com/cbeust/kobalt-intellij-plugin/files/289164/kobalt-intellij-plugin.zip)

@cbeust   Maybe some corrupted version for some reason was uploaded to the repository...
