### ISSUE TITLE
Can't compile a project with multiple modules

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#36]
I'm having trouble compiling a project with two modules from the plugin. It builds fine from the command line. The problem is that the plugin only allows running compile for a single module, not for the whole project. So while from the command line I can do `./kobaltw compile`, the plugin does the equivalent of `./kobaltw PokeKotlin:compile` which doesn't compile the project it's dependent on.

Here's my build file: https://raw.githubusercontent.com/pokesource/pokekotlin/apt/kobalt/src/Build.kt

**Comment by dmitry-zhuravlev** [comment]
Yes, it is a general problem. Because Kobalt doesn't consider dependent modules when you run module related task. @cbeust Maybe Kobalt should consider dependent project when run task for one of the module, like Gradle does? @sargunster At the moment like a workaround you can create Kobalt run configuration and there define "compile" task which will executes for the whole Build.kt file.

**Comment by DevCharly** [comment]
There is now a related Kobalt issue cbeust/kobalt#212

@dmitry-zhuravlev could you please consider to add tasks-without-project to the Kobalt view. E.g. an additional node "All" node in the tree with tasks as children.

**Comment by dmitry-zhuravlev** [comment]
This should be added in a project model which send Kobalt server first. At the moment all task in this model relates to some project and not to the general scope of the build.

**Comment by cbeust** [comment]
@dmitry-zhuravlev Are you saying that it's the Kobalt server that should be sending you this information?

I'm guessing if we have projects `p1` and `p2`, the server should send three sets of tasks:
1. Tasks for all projects
2. Tasks for `p1` only
3. Tasks for `p2` only

Would that fix the problem?

**Comment by cbeust** [comment]
Actually, this can be done at the IDEA plug-in level. Right now, each project data I send to the plug-in contains the tasks for this project:

```
p1:
  p1:compile
  p1:assemble
p2:
  p2:compile
  p2:someOtherTask
```

Once you receive this data, you can create the list of all available tasks by simply keeping everything after `:`, which would give you `compile, assemble, someOtherTask`.

No need for the server to send you additional information.

@dmitry-zhuravlev What do you think?

**Comment by dmitry-zhuravlev** [comment]
> you can create the list of all available tasks by simply keeping everything after :

But if user define some custom task for particular project I guess it shouldn't be added to "all project" scope. It is not clear how to distinguish custom tasks from tasks like "compile" which also exist for all projects. Thats why I think server should send "Tasks for all projects" in this case.

 And I need to recheck if adding tasks in "All" node even possible with external API...

**Comment by cbeust** [comment]
Ok, I can add this to Kobalt itself.

**Comment by dmitry-zhuravlev** [comment]
Commited some preparation stuff for creating task nodes for all projects. @cbeust Ping me after you add tasks in server response payload and I'll add it in tool window tree.

**Comment by cbeust** [comment]
Done. I updated both Kobalt (0.798) and the plug-in with the new payload. `GetDependenciesData` now has an additional field `allTasks`:

```
class GetDependenciesData(val projects: List<ProjectData>, val allTasks: Collection<TaskData>,
        val errorMessage: String?)
```

**Comment by DevCharly** [comment]
For better usability, I'd like to suggest to move the global `Tasks` to the top of the tree.

**Comment by cbeust** [comment]
I've been thinking the same thing, I think the global `Tasks` should be at the top.

**Comment by dmitry-zhuravlev** [comment]
It would be there automatically after EAP becomes release version. I already checked the latest version of IDEA with some changes in external API. So simple keep wait for it 😉

**Comment by cbeust** [comment]
Sounds good!
