### ISSUE TITLE
The plugin doesn't install Kobalt for new users

### ISSUE THREAD

**Issue by sargunv** [cbeust/kobalt-intellij-plugin#39]
The plugin can't be used unless the user has installed Kobalt before.

1) Delete `~/.kobalt`
2) Launch IntelliJ
3) Attempt to create a new Kobalt project

This also happens when the user tries to specify a Kobalt version in the plugin that's different from a version that's installed.

Ideally, the plugin should handle the installation for the user, so a new user can simply install the plugin and use Kobalt from the IDE without worrying about manual installation.

**Comment by dmitry-zhuravlev** [comment]
Agree, I'll improve this...

> This also happens when the user tries to specify a Kobalt version in the plugin that's different from a version that's installed.

Could you please explain this sentence? Usually if you try to change Kobalt distributions which is already present in ~/.kobalt directory you can do it....

**Comment by sargunv** [comment]
Say the user has only Kobalt 0.789 in ~/.kobalt but in the new project wizard enters the path for 0.792 (which doesn't exist). This is the similar to Kobalt not being installed at all, the plugin still needs to install 0.792.

**Comment by dmitry-zhuravlev** [comment]
Yep, thank you. Now it is clear for me. I'll try to improve this.

**Comment by dmitry-zhuravlev** [comment]
@sargunster  For now the plugin will download the newest version if "Always download and apply new versions of Kobalt" is checked. Otherwise this checkbox can be unchecked and other Kobalt version can be chosen.
