### ISSUE TITLE
Can't change the Kobalt home

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#46]
I can't seem to edit the text field or click on the "..." button:

![image](https://cloud.githubusercontent.com/assets/92322/16166452/d64aa440-3497-11e6-9e97-a55d3a52fe37.png)

**Comment by cbeust** [comment]
I have a follow-up question: how do I run the IDEA plug-in with a local `kobalt.jar` now? It looks like the information in `Constants` is now ignored:

```
        val MIN_KOBALT_VERSION = "0.818"

        /** If true, will launch kobalt found in ~/kotlin/kobalt/libs/kobalt-$DEV_VERSION.jar */
        val DEV_MODE = false
```

**Edit**: I just fixed it and restored these constants.

**Comment by dmitry-zhuravlev** [comment]
If you uncheck "Always download and apply new version" the field to select custom distribution of Kobalt will be enabled. Actually this is a switch to allow user to choose which behavior he want: always to pick the newest version or manually select the given distribution and don't allow to change it to the newest if available.
