### ISSUE TITLE
expose task checkVersions in the tool window

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt-intellij-plugin#49]
It would be cool if the intellij plugin exposed/supported this task that is available from the command line

``````
[8:32]  
 ```$ ./kobaltw --checkVersions
New versions found:
       com.beust:klaxon:0.14
       org.testng:testng:6.9.5
``````

**Comment by cbeust** [comment]
Good point. The window only exposes tasks right now but some command line
parameters might be useful.

We could also think about being able to have a "Kobalt launch
configuration" where users can invoke Kobalt as if they were launching it
from the shell (might be just a tiny wrapper over invoking `MainKt` with
the passed parameters). This way, they can launch specific line parameters
and task.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
It is already "Script parameters" in Kobalt run configuration. So you could specify --checkVersions there.

**Comment by pabl0rg** [comment]
That is awesome, but refactoring that flag into a task might make the feature more discoverable/usable

**Comment by dmitry-zhuravlev** [comment]
Yep, in this case it should be transformed into standard  task which should be implemented within Kobalt.

**Comment by cbeust** [comment]
It's not always easy to determine what should be a task and what should be
a command line parameter.

So far, I've tried to stick to "A task is part of your build" so any other
"meta" command like "checkVersions" or "update" (Kobalt's self update) of
the plug-ins belongs to a command line parameter.

Maybe I could change the philosophy and make everything (or a lot more
things anyway) a task, I'm not sure.

## 

Cédric

**Comment by pabl0rg** [comment]
What would be the disadvantages of making everything (or at least checkVersions and update) a task?

**Comment by cbeust** [comment]
None I can think of, really.

## 

Cédric

**Comment by dmitry-zhuravlev** [comment]
You are right, in many cases it hardly to say what should be a task or a parameter. But things related to build like versions and Kobalt update could be a task, and definitely things like --dev, --server, --log it is a parameters because they describe not the build itself but the way how kobalt launches: it is a configuration of Kobalt launch.

**Comment by pabl0rg** [comment]
Good points @dmitry-zhuravlev

**Comment by cbeust** [comment]
Ok so I'm fine making `checkVersions` and `update` tasks. Looking at `Args.kt`, it's not quite clear to me which ones should become tasks as well, happy to hear suggestions.

**Comment by pabl0rg** [comment]
The others make a lot more sense as command-line arguments.

**Comment by cbeust** [comment]
FYI, I found a philosophical objection to having `checkVersions` and `update` as tasks. Tasks receive the project in parameter:

```
    @Task(name = "checkVersions", description = "Display all the outdated dependencies")
    fun taskCheckVersions(project: Project) : TaskResult {
```

In other words, a task is run once for each project (e.g. three times for Kobalt, which has three projects).

Which obviously doesn't make sense for `update` and `checkVersions`.

**Comment by pabl0rg** [comment]
Would it make sense for checkVersions since each project can have different dependencies?

**Comment by cbeust** [comment]
@pabl0rg Oops of course...

**Comment by cbeust** [comment]
Ok done, these two are now tasks (but they are still command line parameters as well, for now).

**Comment by pabl0rg** [comment]
Great!  Is the update task called update?  I wonder if installWrapper or installKobaltw would be more intuitive (sorry I didn't suggest that sooner).

**Comment by dmitry-zhuravlev** [comment]
@pabl0rg 
This issue about `checkVersions` and it present and works. Maybe you mean this issue https://github.com/cbeust/kobalt-intellij-plugin/issues/28 when talking about `installWrapper` and `installKobaltw`?

**Comment by pabl0rg** [comment]
Right, sorry.  Though update was mentioned in this issue as well.
