### ISSUE TITLE
500 Internal Error when importing Kobalt project

### ISSUE THREAD

**Issue by norswap** [cbeust/kobalt-intellij-plugin#51]
Here's what I'm getting:

![error](http://i.imgur.com/nvWrrSC.png)

The relevant log: http://pastebin.com/jRMZ9jCz

**Comment by cbeust** [comment]
@dmitry-zhuravlev :

Note that it's a 500, so the server is up and running but it threw when trying to run `getDependencies()`. It would be nice to capture the server stack trace in the IDEA log (and I'll look into sending that stack trace in the protocol packet too).

**Comment by norswap** [comment]
Actually, when starting IntelliJ I'm getting the following:

![](http://i.imgur.com/Gri8EYl.png)

(On IntelliJ 15.0.6 on Windows)

I also tried on OS X, and I get neither errors there.

**Comment by dmitry-zhuravlev** [comment]
I guess you running old version of plugin because of IDEA 15.0.6. Note that some features required new IDEA 2016 and hence incompatible with old versions of IDEA.

**Comment by cbeust** [comment]
@dmitry-zhuravlev Is it possible to get the plug-in to run on these old versions?

**Comment by dmitry-zhuravlev** [comment]
Some of the IDEA bugs was fixed in 2016 version. Also the old plugin version should be used with some old Kobalt version. I'm not sure that we should take care about old versions. Of course it would be always better for users which have an old version, but it lead to additional effort to support many (how many?) versions of IDEA.

**Comment by norswap** [comment]
I'm too pampered by auto-update, I didn't even realize I didn't have the latest version on Windows :)
I updated, and it works alright :+1:

**Comment by cbeust** [comment]
@dmitry-zhuravlev Ok, was just checking. I think right now, it's fine to tell people they need to update IDEA to get the latest version.

@norswap Great to hear it, closing the issue.
