### ISSUE TITLE
AssertionError on opening project created by kobalt plugin

### ISSUE THREAD

**Issue by jkbbwr** [cbeust/kobalt-intellij-plugin#52]
Similar to #43 
Under version 1.114 idea will now show 

```
17:46:00 AssertionError: Kotlin library should exists when adding sources root
```

each time a kobalt project is opened, the user can click `configure for java` and the assertion is thrown but everything works fine.

**Comment by dmitry-zhuravlev** [comment]
Yeach, I seen it before but only on some project. Original assertion comes from Kotlin plugin so I suspect that this is an issue of Kotlin plugin. Do you have a latest Kotlin plugin installed? Could you reproduce it with a new Kobalt based project created with plugin's wizard?

**Comment by dmitry-zhuravlev** [comment]
@jkbbwr Is it still valid for you with the latest Kobalt version and the latest plugin?

**Comment by jkbbwr** [comment]
Don't know haven't been working with it for a while now
