### ISSUE TITLE
Gradle tasks run from the Gradle tab are turn into Kobalt Run/Debug Configurations

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt-intellij-plugin#53]
Using **IntelliJ IDEA 2016.1.3** w/ **Kobalt plugin 1.114**.

Started with a Kobalt project and added a Gradle build file to the `Gradle projects` tab.

Gradle task will run fine from the tab, but will then fail from the `Run` menu.

**Comment by dmitry-zhuravlev** [comment]
"... will then fail from Run menu"--> Do you mean invalid run configuration created? Seems like 
https://github.com/cbeust/kobalt/issues/198

So the fix for this still not present in the release version of IDEA.

**Comment by ethauvin** [comment]
Yeap, same. Closing.
