### ISSUE TITLE
Support bringing in sources jars to support jumping into dependencies.

### ISSUE THREAD

**Issue by kyonifer** [cbeust/kobalt-intellij-plugin#54]
It would be nice to be able to hit Ctrl+B and jump into the source of dependencies. Trying to add a jar with a sources classifier manually to the build file as a compile dependency still brought in the binary jar.

**Comment by dmitry-zhuravlev** [comment]
Should be supported by Kobalt first. @cbeust Like a future request: Kobalt should download sources for dependencies (if present) and cache it in repository folder. Then Kobalt's server should send location of sources to plugin.

**Comment by cbeust** [comment]
Kobalt doesn't download sources by default (for performance and hard drive space reasons) but you can force the download with a `resolve` and the `sources` qualifier:

```
$ kobaltw --resolve org.testng:testng::sources:6.9.11
$ ls ~/.kobalt/cache/org/testng/testng/6.9.11                                                                                         _remote.repositories            testng-6.9.11-sources.jar.sha1  testng-6.9.11.jar.sha1          testng-6.9.11.pom.sha1
testng-6.9.11-sources.jar       testng-6.9.11.jar               testng-6.9.11.pom
```

That would be one way of doing it.

Another one would be to use IDEA's own mechanism: I saw that I can download sources from IDEA and I can then specify whether it's "From Java" or "From Maven". @dmitry-zhuravlev are you familiar with that mechanism?

**Comment by dmitry-zhuravlev** [comment]
Actually it depends on build tool. It seems that Gradle always download all sources (if available) and cache it to `~/.gradle/caches`. From the one hand it is very handy but from another hand I agree: it can affect at least time of dependency resolving and hard drive space. 

Maven IDEA plugin have some buttons in tool window to initiate download of sources:

![image](https://cloud.githubusercontent.com/assets/6297697/17138400/c3a6ada0-5348-11e6-9092-4467ae11d109.png)

But also there is some internal mechanism when you click on classes without sources:
![image](https://cloud.githubusercontent.com/assets/6297697/17138448/f711c3fa-5348-11e6-911f-0afe44ce4142.png)

If "Download" pressed then IDEA will download it to `~/.ideaLibSources` folder and attach it to needed library. This is internal mechanism of IDEA and it works for Kobalt based project too.

So the question at the moment is: should we support `kobaltw --resolve {dependency}` functionality via additional button in tool window or not?

At the moment it seems that internal mechanism of IDEA to download and attach sources quite useful and enough...

**Comment by cbeust** [comment]
Agreed, I think IDEA's internal mechanism is good enough.

## 

Cédric

**Comment by kyonifer** [comment]
@dmitry-zhuravlev any chance you might be able to revisit this issue? I'm unable to get the "Download" button workaround to work here (always says `Sources not found: Sources for '**.jar' not found`) and downloading sources manually is tedious.

**Comment by dmitry-zhuravlev** [comment]
@kyonifer I guess that you are behind corporate proxy... I filled some bug about it https://youtrack.jetbrains.com/issue/IDEA-170595 It seems that configured HTTP proxy ignored for such functionality.

>downloading sources manually is tedious

In general I agree with you. From another hand still there is places with bad connection to internet and download sources in this case will take additional bandwidth effort.

Maybe we need to think about implementation additional parameter in Kobalt (e.g. `--resolveSources`). This parameter could be added in plugin settings like an additinal checkbox. So if the user want, he could enable  it in plugin and Kobalt will try to download sources for all dependencies.
@cbeust What do you think?

**Comment by cbeust** [comment]
Before I switched to Aether, `./kobaltw --resolve xxx` would also force a download of the sources. I just checked and this functionality went away with the migration, but I can bring it back.

Would this help, @dmitry-zhuravlev? When the user says they want to download the sources, could you then just issue a `--resolve` of the dependency and point to these sources?

Also, it looks like IDEA already has this mechanism in place: when you press "Download sources", it sees if this class file is part of a Maven dependency and downloads it, any idea why this doesn't seem to work for Kobalt?

**Comment by kyonifer** [comment]
> I guess that you are behind corporate proxy... I filled some bug about it https://youtrack.jetbrains.com/issue/IDEA-170595 It seems that configured HTTP proxy ignored for such functionality.

I'm behind a firewall, but no HTTP proxy is needed and in general outbound connections should work. The gradle plugin's sources-grabber as well as normal `./kobaltw` usage works fine without a proxy. Is there a way to coax a better error out of intellij? The idea.log doesn't have anything related in it.

**Comment by dmitry-zhuravlev** [comment]
> Would this help, @dmitry-zhuravlev? When the user says they want to download the sources, could you then just issue a --resolve of the dependency and point to these sources?

@cbeust I think that manual mechanism is already present and when https://youtrack.jetbrains.com/issue/IDEA-170595  will be fixed I hope it will work in all cases.
By the way I'm talking about something like `--resolveSources` functionality which will be helpfull to download sources\javadoc for all dependencies mentioned in `Build.kt`. This will be very helpful because I like the way what Gradle do by default: download all sources (of course in case if I have a good bandwidth ;) )

>Also, it looks like IDEA already has this mechanism in place: when you press "Download sources", it sees if this class file is part of a Maven dependency and downloads it, any idea why this doesn't seem to work for Kobalt?

For me it works but only in case if there is no HTTP proxy in between me and internet.

**Comment by dmitry-zhuravlev** [comment]
I did some preparation in IDEA plugin: 
Now plugin is able to scan directory where Kobalt download dependencies jars. If it finds `*sources.jar` and `*javadoc.jar` then it will be attached to corresponding library.

So it would be good to have `--resolveSources` `--resolveJavadoc` parameters in Kobalt server. If the server receive `--resolveSources` then it should download all sources for all dependencies mentioned in `Build.kt`.
The same things should be happen with `--resolveJavadoc` parameter but for javadocs.

**Comment by cbeust** [comment]
I like the idea of doing that but just for the server, will file an issue. Thanks for the suggestion!

**Comment by dmitry-zhuravlev** [comment]
Plugin 1.124 and the latest Kobalt have the ability to specify download sources/javadoc policy for all dependencies specified in `Build.kt`:
![image](https://cloud.githubusercontent.com/assets/6297697/24762221/6b1e7e58-1af6-11e7-9f25-93490a26a4f0.png)

**Comment by kyonifer** [comment]
Awesome-- this works perfectly for me now, thanks for the addition!
