### ISSUE TITLE
Syncing should preserve the compiler level

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#59]
Whenever I sync, the plug-in resets the compiler level to 1.6:

![image](https://cloud.githubusercontent.com/assets/92322/22666119/4371c832-ec6c-11e6-86dd-b1da8ff596e0.png)

This settings should be saved before sync and restored afterward.

**Comment by dmitry-zhuravlev** [comment]
@cbeust 
During the initial import there is no way to determine which language level and SDK version should be used. 1.6 it is a default one. 
I can set the level explicitly to 1.8 but what about users which still have 1.7 or even 1.6?

The consequence re-import recreate the the IDEA project from scratch and there is no way to store something in between sync.

E.g. Gradle daemon send to IDEA plugin the following information: `String jdkVersion, String languageLevel`.
Maybe Kobalt server could do the same? Kobalt server instance can determine such information (e.g. by `Build.kt`) and return it to IDEA plugin.

FYI some snippet from Gradle:
```
allprojects {
    tasks.withType(JavaCompile) {
        sourceCompatibility = '1.7'
        targetCompatibility = '1.7'
    } 
}
```

**Comment by cbeust** [comment]
Let's use 1.8 as default, then. Users using an older version will be a bit inconvenienced but they are probably a minority.

Otherwise, sure, Kobalt could send you this information, can you file an issue for Kobalt for this?

Thanks!

**Comment by dmitry-zhuravlev** [comment]
> Users using an older version will be a bit inconvenienced but they are probably a minority.

:) Probably can agree: lets set default 1.8 to majority first.
FYI created the corresponding issue https://github.com/cbeust/kobalt/issues/371
