### ISSUE TITLE
Need better error reporting

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#60]
If you try to sync the current plug-in with a Kobalt > 0.920, you get:

![image](https://cloud.githubusercontent.com/assets/92322/22759590/d47e0c0e-ee07-11e6-9e57-f891761aeeb1.png)

As we discussed previously, this is mostly due to the 1.0.6 / 1.1.0-beta Kotlin compiler discrepancy (the sync works fine with 0.920 and below), but I really wanted to make sure that such was the case, however, I can't get any stack trace from anything (there's nothing in the IDEA event log and the stack trace in `idea.log` is not helpful).

@dmitry-zhuravlev, do you know what exactly is causing this 500 and how we could surface it?

**Comment by dmitry-zhuravlev** [comment]
@cbeust I also see this problem starting from 0.922. However 0.919 works for me....

**Comment by dmitry-zhuravlev** [comment]
By the way I tried from master branch.... But when I swithed back to migration branch all seems to be fine.

**Comment by cbeust** [comment]
Were you able to find out exactly what's causing this 500? I would expect to see some stack trace with a bytecode error or some `ClassDefNotFound`, but I'm still not quite understanding how the version of the remote Kobalt server matters: it's a JSON call to a remote process, why would it matter what version of `kotlinc` was used to compile that remote process?

**Comment by dmitry-zhuravlev** [comment]
I didn't see this issue any more. So probably closing it.
