### ISSUE TITLE
Handle `plugins()` correctly

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#62]
We need to support `plugins()` correctly. Currently, this build does not compile:

```
...
import com.beust.kobalt.plugin.linecount.*

val bs = buildScript {
    plugins("com.beust.kobalt:kobalt-line-count:0.23")
}

val p = project {
    name = "klaxon"
    group = "com.beust"
    artifactId = name
    version = "0.29"

    lineCount {
        suffix = "*kt"
    }
}
```

In the latest version of Kobalt, the server returns an additional property `pluginDependencies` in the `GetDependenciesData` structure:

```
    class GetDependenciesData(val projects: List<ProjectData> = emptyList(),
            val allTasks: Collection<TaskData> = emptySet(),
            val pluginDependencies: List<File> = emptyList(),
            val errorMessage: String?) {
```

These files (jar files) should be added as dependencies to the `Build.kt` module, which will allow the build file above to build after a sync.

@dmitry-zhuravlev, let me know if you have any questions!

**Comment by dmitry-zhuravlev** [comment]
Yep, seems we need to do some adjustments here. At the moment `Build.kt` module is handled differently from other modules which is processed within IDEA's external api. Maybe I'll put `Build.kt` also into processing.

@cbeust  However why `pluginDependencies` is type of `List<File>`? I guess it should be `List<DependencyData>`.

**Comment by cbeust** [comment]
Oops you're right, `pluginDependencies` is now a `List<DependencyData>`:

https://github.com/cbeust/kobalt/blob/master/src/main/kotlin/com/beust/kobalt/app/remote/RemoteDependencyData.kt#L201

**Comment by cbeust** [comment]
Working great!

![image](https://cloud.githubusercontent.com/assets/92322/23135334/07bf65c4-f74d-11e6-9d5e-0e74a4820312.png)
