### ISSUE TITLE
Build.kt should not be compiled in kobaltBuild/classes

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#68]
Hi @dmitry-zhuravlev,

`Build.kt` is getting compiled into `kobaltBuild/classes` by default:

```
./kobaltBuild/classes/BuildKt$bs$1.class
./kobaltBuild/classes/BuildKt$kobaltApp$1$1.class
./kobaltBuild/classes/BuildKt$kobaltApp$1$2.class
```

which is very bad since it means the build file will end up packaged with the application, and it will interfere with other builds.

How about compiling it inside `.kobalt/build/buildFile` or maybe even `/tmp`?

**Comment by dmitry-zhuravlev** [comment]
Hi @cbeust Hm... you are right. But maybe it is a good idea to put it in the same folder like Kobalt itself do. The intention is to reuse the output classes from Kobalt within IDEA and vise versa and not compile it twice. But I guess that this will work only in case if IDEA compile it with the equal classpath and equal Kotlin compiler like Kobalt server do....

**Comment by cbeust** [comment]
Any location besides `kobaltBuild` is fine with me :-)

**Comment by dmitry-zhuravlev** [comment]
Done. Now the output of `Builld.kt` module will be `kobalt/out/classes`

**Comment by cbeust** [comment]
Great, thanks! Are you publishing the new plug-in yourself?

**Comment by dmitry-zhuravlev** [comment]
Yep, tried to upload the 1.122 version and it works fine ;)
