### ISSUE TITLE
Unable to open kobalt projects in IU-2017.1

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt-intellij-plugin#69]
I'm not able to open Kobalt projects in IDEA 2017.1

Here's a sample project: https://github.com/dittert/kobaltfailure

Error message after import: 
![this should not be shown 2017-03-23 11-11-35](https://cloud.githubusercontent.com/assets/1113632/24283007/511843ce-1063-11e7-82f9-d9ad43346aaf.png)

It opens in 2016.3 without errors.

**Comment by cbeust** [comment]
@dmitry-zhuravlev we encountered that with @dittert, it seems to be a regression in 2017.1 (not sure if it's Kobalt's or IDEA's).

**Comment by dmitry-zhuravlev** [comment]
Just yesterday worked with Kobalt and IDEA 2017.1 and have no problem. I'll recheck. @dittert do you have also the latest Kotlin plugin installed?

**Comment by dittert** [comment]
Yes, I'm using 1.1.1-release-IJ2017.1-1.

**Comment by dmitry-zhuravlev** [comment]
Tried to reproduce by using https://github.com/dittert/kobaltfailure project.
Have successfull import:
![image](https://cloud.githubusercontent.com/assets/6297697/24289463/6dbee350-1092-11e7-881c-a613fed298e4.png)
Also take a look on highlighted dependencies. Such Kotlin runtime dependencies could be added by using `Kotlin not configured notification` (use the latest 1.122 Kobalt plugin version):
![image](https://cloud.githubusercontent.com/assets/6297697/24289707/7c2c5ed0-1093-11e7-98fa-9f75e32846cb.png)

@dittert Do you see any errors in `idea.log`? (can be found in `{HOME_DIR}/.IntelliJIdea2017.1/system/log`)

**Comment by dittert** [comment]
This is the only thing thing that is related to kobalt:

```
2017-03-23 19:31:52,787 [   7429]   INFO - CompilerBackwardReferenceIndex - /Users/dirk/Library/Caches/IntelliJIdea2017.1/compile-server/kobaltfailure_c6265bfc/backward-refs/version (No such file or directory) 
java.io.FileNotFoundException: /Users/dirk/Library/Caches/IntelliJIdea2017.1/compile-server/kobaltfailure_c6265bfc/backward-refs/version (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at org.jetbrains.jps.backwardRefs.CompilerBackwardReferenceIndex.versionDiffers(CompilerBackwardReferenceIndex.java:162)
    at com.intellij.compiler.backwardRefs.CompilerReferenceReader.exists(CompilerReferenceReader.java:114)
    at com.intellij.compiler.backwardRefs.CompilerReferenceServiceImpl.a(CompilerReferenceServiceImpl.java:140)
    at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
``` 
What does work: 

- open directory in 2016.3 and import kobalt 
- open directory in 2017.1

Whenever I try to open it without the ```.idea``` folder present, it fails.

**Comment by cbeust** [comment]
I confirm the bug: I just upgraded to 2017.1 on Windows and I can no longer import anything The dialog appears as soon as I press "Ok". The only line generated by the Kobalt plug-in in the log is:

```
C:\Users\Cedric\.kobalt\wrapper\dist\kobalt-1.0.23.zip already present, no need to download it 
```

![image](https://cloud.githubusercontent.com/assets/92322/24320191/850dab08-10ed-11e7-98b3-4abd7cfabbc4.png)

**Comment by dmitry-zhuravlev** [comment]
@cbeust Tried to launch Kobalt server manually and it failed:
`java -jar kobalt-1.0.23.jar --log 3 --force --dev --server`

```
Parsed plugin XML file, found: kobalt
              __ __           __              __   __ 
             / //_/  ____    / /_   ____ _   / /  / /_
            / ,<    / __ \  / __ \ / __ `/  / /  / __/
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_  
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  1.0.23

*****
***** ERROR /Users/dmitry/.kobalt/wrapper/dist/kobalt-1.0.23/kobalt/wrapper/kobalt/src/Build.kt does not exist
```

Any hint?

**Comment by cbeust** [comment]
Mmh weird, seems to be working for me:

```
$ java -jar ~/.kobalt/wrapper/dist/kobalt-1.0.23/kobalt/wrapper/kobalt-1.0.23.jar  --server --force
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  1.0.23

KobaltServer listening on port 1234
[Thread-2] INFO org.eclipse.jetty.util.log - Logging initialized @2321ms
[Thread-2] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - == Spark has ignited ...
[Thread-2] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >> Listening on 0.0.0.0:1234
[Thread-2] INFO org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
[Thread-2] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@3a0ce147{/,null,AVAILABLE}
[Thread-2] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@ea5d682{HTTP/1.1,[http/1.1]}{0.0.0.0:1234}
[Thread-2] INFO org.eclipse.jetty.server.Server - Started @2504ms
```

**Comment by cbeust** [comment]
Oh you must be launching it from a directory that doesn't have a build file. I guess I should make it optional to have a build file.

**Comment by cbeust** [comment]
Fixed in 1.0.24.

**Comment by dmitry-zhuravlev** [comment]
Finally reproduced and fixed mentioned bug with "project directory is already taken". Some small forgotten "null" reference could be a reason :)

**Comment by cbeust** [comment]
Awesome, I was getting tired of tweaking my way out of it (FYI I was manually modifying the `.iml`).

Please let us know when the new plug-in is available.

Thanks, @dmitry-zhuravlev !
