### ISSUE TITLE
Provide an option to make Kobalt sources available

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt-intellij-plugin#70]
As Egon, the maintainer of our build scripts, I'd like to be able to access the source code of Kobalt directly from my build scripts in order to not need to repeatedly configure this manually.

**Details**
IDEA shows only method signatures of Kotlin code by default. All the implementation is hidden behind ```/* compiled code */```.  This would also be very helpful while working on build scripts because you can just step into the implementation. I'm not really concerned with the additional size of the sources (after all, building already means downloading 30% of the internet anyway).

There could be an option ```sources=true``` in ```kobalt-wrapper.properties``` that triggers the download of sources. The IDE plugin add ```kobalt-plugin-api-1.0.23-sources.jar``` and ```kobalt-1.0.23-sources.jar``` to the Kobalt jar.

**Comment by dmitry-zhuravlev** [comment]
Should be done on Kobalt side first. See https://github.com/cbeust/kobalt/issues/237

**Comment by dmitry-zhuravlev** [comment]
Kobalt sources now packaged within zip distribution since 1.0.68
Also Kobalt and plugin have ability to download sources/javadoc for dependencies mentioned in `Build.kt`
