### ISSUE TITLE
Running tasks creates run configurations of incorrect type

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt-intellij-plugin#72]
The Kobalt window shows something like this:

![tasks](https://cloud.githubusercontent.com/assets/1113632/24324227/d00138a6-1182-11e7-94cc-e61921777b7a.png)

Steps to reproduce:

- double click on task clean to run it

IDEA creates the following run configuration:

![generated confing](https://cloud.githubusercontent.com/assets/1113632/24324235/0cf56ade-1183-11e7-9ee9-b3b37e7b0800.png)

This is a Gradle run configuration that will fail to run if you click on the green arrow. The plugin should create a Kobalt run configuration instead.

IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3

Plugin version: 1.122

**Comment by dmitry-zhuravlev** [comment]
It's a long term issue... should be fixed in future versions of IDEA, see https://youtrack.jetbrains.com/issue/IDEA-168172

**Comment by dmitry-zhuravlev** [comment]
Fixed in IntelliJ IDEA 2017.1.1 Build #IU-171.4073.35, built on April 6, 2017
