### ISSUE TITLE
Allow to specify profiles in the IDE plugin

### ISSUE THREAD

**Issue by dittert** [cbeust/kobalt-intellij-plugin#73]
As Bob, the maintainer of our builds, I'd like to be able to configure the profiles that are used by the IDE plugin in order to use development versions of some libraries.

**Details**
Profiles can have a great deal of influence on what happens in a build script. Here's an example:

```
val dev by profile()

val bs = buildScript {
    if (dev) {
        plugins(file(homeDir("projects/linecount/kobaltBuild/libs/linecount-0.3-SNAPSHOT.jar")))
    } else {
        plugins("tfo.kobalt:linecount:0.2")
    }
}
```

This example influences the tasks that should be available in the Kobalt window (because different versions of the plugin might supply different tasks). 

Here's another one:
```
val dev by profile()

dependencies {
    if (dev) {
        compile("junit:junit:4.12")
    } else {
        compile("junit:junit:4.11")
    }
}
```

Here, the project dependencies that should be used in IDEA for code completion and code navigation depend on the profile that is actually being used (because different versions of JUnit might expose different APIs). 

I believe that both scenarios are quite common when working on Kobalt based projects.

**Comment by dmitry-zhuravlev** [comment]
Kobalt already have profiles see http://beust.com/kobalt/documentation/index.html

So you can specify '-profiles' parameter in IDEA Kobalt run configuration.

**Comment by dittert** [comment]
I know that I can specify profiles in run configurations through command line options.

But as I pointed out in the feature request, the tasks that are shown by the IDEA Kobalt window and the project dependencies used by IDEA may also be dependent on profiles! And currently there is no way to specify which profile should be used by Kobalt to configure the IDEA project. As I understand it, this task is not performed by a run configuration. If the IDE only supports the baseline profile that would quite limit the usefulness of profiles and downgrade them to boolean toggles that need to be set in ```Build.kt```.

The same basic reasoning probably also applies to [variants](http://beust.com/kobalt/plug-ins/index.html#variants) (i.e. product flavours and build types).

**Comment by cbeust** [comment]
Maybe the `Kobalt` settings panel in IDEA should let the user specify a list of profiles? And whenever this list is changed, the plug-in triggers a sync to update its dependencies.

@dmitry-zhuravlev what do you think?

**Comment by dittert** [comment]
Those calls to `by profile()` should be a nice hook to collect all of them when `Build.kt` is evaluated. The delegate also knows the name of the property.

**Comment by cbeust** [comment]
Interestingly, the `profile()` delegate does nothing, it's mostly used as a marker. Kobalt actually needs to locate these calls in the build file, so it has to parse the build file and do its work during that parsing, instead of just relying on the call to `profile()` (which it could, but again, this is not enough: I need the line number where that call is made so I can replace it).

As for the IDEA plug-in, I don't think it should ever care what these values are, except in this hypothetical "profiles" settings we're discussing. After that, it just hands these profiles to the Kobalt server and waits for the dependencies in return.

**Comment by dmitry-zhuravlev** [comment]
>Maybe the Kobalt settings panel in IDEA should let the user specify a list of profiles? And whenever this list is changed, the plug-in triggers a sync to update its dependencies.

Also thought in this direction.... So I will add additinal field in Kobalt settings and will send additinal query parameter `profiles` in server call `/v1/getDependencyGraph`

**Comment by cbeust** [comment]
Sounds good, @dmitry-zhuravlev.

**Comment by dmitry-zhuravlev** [comment]
Added field:
![image](https://cloud.githubusercontent.com/assets/6297697/24360904/404d3d96-1311-11e7-88fe-3fe3592ae659.png)

This string will be sended to `/v1/getDependencyGraph?profiles=....`
@cbeust now you can process it inside Kobalt. Let me know when you add it inside Kobalt and we will test how it works ;-)

**Comment by cbeust** [comment]
Thanks, Dmitry. Can you publish the plug-in with this change?

**Comment by dmitry-zhuravlev** [comment]
@cbeust  Done. v1.123 uploaded with this change.

**Comment by dittert** [comment]
Where do I find that setting?

**Comment by dmitry-zhuravlev** [comment]
@dittert 
Plugin version 1.123
Kobalt version since 1.0.33

In settings:
![image](https://cloud.githubusercontent.com/assets/6297697/24553636/80bf1f3c-1633-11e7-87c9-8f59cce23354.png)
Should be text filed present:
![image](https://cloud.githubusercontent.com/assets/6297697/24553663/9042e560-1633-11e7-8661-f84c7d39bca4.png)
