### ISSUE TITLE
Deprecate buildFile in "/v1/getDependencyGraph"

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#74]
Starting in 1.0.27, `buildFile` is deprecated in this call and should be replaced with `projectRoot` pointing to the root of the project. Kobalt will figure out how to find the correct build file.

Old:

`/v1/getDependencyGraph?buildFile=/users/cedric/java/jcommander/kobalt/src/Build.kt`

New:

`/v1/getDependencyGraph?projectRoot=/users/cedric/java/jcommander`

This is a first step toward Kobalt supporting multiple build files.

**Comment by dmitry-zhuravlev** [comment]
>This is a first step toward Kobalt supporting multiple build files.

Looks promising :-)
