### ISSUE TITLE
Add support for multiple build directories

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#76]
As of 1.0.44, `getDependenciesGraph` returns an additional `buildContentRoots` parameter:

```
{
   "projects": [],
   "allTasks": [],
   "pluginDependencies": [],
   "buildContentRoots": [
      "kobalt",
      "module/test/kobalt"
   ]
}
```

Each item in this array should be added as a Content Root for the `Build.kt` module, and then, each of them should add a source directory called `"src"`.

For the example above, this means that from the root of the project, both `kobalt/src` and `modules/test/kobalt/src` contain build files.

**Comment by dmitry-zhuravlev** [comment]
@cbeust Is it possible, that some of the directories mentioned in `buildContentRoots` not exist?

**Comment by cbeust** [comment]
No, this should not happen.
