### ISSUE TITLE
Occasionally, IntelliJ cannot connect to Kobalt with: 'Error:Software caused connection abort: recv failed'

### ISSUE THREAD

**Issue by rhencke** [cbeust/kobalt-intellij-plugin#77]
This is on:
* Windows 10 (version 1607, OS build 15031.0)
* IntelliJ IntelliJ IDEA 2017.1 (Build #IU-171.3780.107)
    * JRE: 1.8.0_112-release-736-b13 amd64
    * JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Kobalt plugin 1.123
* Kobalt version 1.0.44

When attempting to synchronize a Kobalt project, it will sometimes error out with the following message:

```
Error:Software caused connection abort: recv failed
```

For example, one set of steps that reproduces this is:
1) Open IntelliJ
2) Open an existing Kobalt project
3) Click the 'Refresh all Kobalt projects' button in the Kobalt tool window.

**Comment by ethauvin** [comment]
```
./kobaltw --server --force
```
before starting IDEA is a workaround until it is fixed.

**Comment by cbeust** [comment]
I see this `Error:Software caused connection abort: recv failed` very often indeed, and pretty much whenever I open a project.

**Comment by dmitry-zhuravlev** [comment]
Do you all see it on Windows?
"Error:Software caused" can be simple ignored. I always have this on Windows and it seems like
http://stackoverflow.com/questions/2126607/official-reasons-for-software-caused-connection-abort-socket-write-error

So probably I can hide this error message or someone can suggest how to close websocket gracefully without send this error back to client?

**Comment by dittert** [comment]
No, I'm seeing this on OS X as well.

**Comment by dmitry-zhuravlev** [comment]
@cbeust The mentioned problem can be fixed by remove explicit `session.close()`
inside `onWebSocketConnect` callback:
https://github.com/cbeust/kobalt/blob/23bbcd4d84f65ae5cfb8f06750442dd53273ed36/src/main/kotlin/com/beust/kobalt/app/remote/GetDependencyGraphHandler.kt#L121-L121

It seems that this `close()` invocation prevents websocket client inside IDEA plugin to disconnect gracefully.

**Comment by cbeust** [comment]
I'll remove it and get back to you.

**Comment by cbeust** [comment]
Done and deployed in 1.0.48.
