### ISSUE TITLE
Plugin not longer working after Kotlin 1.1.2 update.

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt-intellij-plugin#80]
All the Kobalt projects that I have updated to Kotlin 1.1.2, per IDEA's popup recommendation, are no longer functional.

They get into the following loop over and over:

![2017-04-27 16_55_52-kobalt-exec - k__kotlin_kobalt-exec - execplugin kt - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25512783/1a1ae538-2b85-11e7-9564-e299af1c1538.png)
![2017-04-27 16_56_12-kobalt-exec - k__kotlin_kobalt-exec - execplugin kt - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25512784/1dbc4a7e-2b85-11e7-9218-05caeca16522.png)
![2017-04-27 16_56_30-kobalt-exec - k__kotlin_kobalt-exec - execplugin kt - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25512786/212ff7c8-2b85-11e7-9eb4-dc49088a4d2e.png)
![2017-04-27 16_58_20-kobalt-exec - k__kotlin_kobalt-exec - execplugin kt - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25512790/2462259c-2b85-11e7-94ec-ebd1d298cc26.png)

I've tried selecting `as Kotlin (Kobalt) module` but that just throws an error.

**Comment by ethauvin** [comment]
Fix didn't help. The only difference I could see is that now I can select `as Kotlin (Kobalt) module`, which does stop the loop behavior, but now it is not resolving dependencies:

![2017-04-28 09_19_06-kobalt-exec - k__kotlin_kobalt-exec - kobalt-exec - _src_main_kotlin_net_](https://cloud.githubusercontent.com/assets/705618/25537633/240434fe-2bf4-11e7-9372-d55b930b7a62.png)

**Comment by ethauvin** [comment]
Any progress on this? Still can't use the plugin while it's looping like that.

**Comment by cbeust** [comment]
For what it's worth, everything seems to be working for me (both on MacOS and Windows).

@dmitry-zhuravlev, any idea what's going on with Eriks' configuration?

**Comment by ethauvin** [comment]
To be sure I created a new project:

```
kobaltw --init kotlin
```

And imported it into IDEA:

![2017-05-01 11_19_41-plugin-test - k__test_plugin-test - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25589364/29a67e20-2e61-11e7-97e6-ad039048e80a.png)
![2017-05-01 11_20_06-plugin-test - k__test_plugin-test - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25589366/2b9f7d62-2e61-11e7-8ae3-55e8a19dcfc5.png)
![2017-05-01 11_20_18-plugin-test - k__test_plugin-test - intellij idea 2017 1 2](https://cloud.githubusercontent.com/assets/705618/25589367/2e03c072-2e61-11e7-9807-b1238a8af2a8.png)
![2017-05-01 11_21_55-plugin-test - k__test_plugin-test - plugin-test - _src_main_kotlin_com_ex](https://cloud.githubusercontent.com/assets/705618/25589329/0d6b055a-2e61-11e7-8db6-a4eb19c5a97e.png)
![2017-05-01 11_22_32-plugin-test - k__test_plugin-test - plugin-test - _src_main_kotlin_com_ex](https://cloud.githubusercontent.com/assets/705618/25589334/0fcc4e62-2e61-11e7-8095-88af7532d24b.png)

**Comment by dmitry-zhuravlev** [comment]
@ethauvin I think the problem here that you choose not proper Kotlin lib configurator.
The proper one is `as Kotlin (Kobalt) module`. The rest configurators have no idea about Kobalt project and cannot adjust the `Build.kt` in corresponding way. 

Also there was a dissucussion with @cbeust  about sending Kotlin libs directly to plugin when refresh button pressed: **https://github.com/cbeust/kobalt-intellij-plugin/issues/79#issuecomment-293222938**
In case if we implement such behaviour the `Configure Kotlin` tooltip will be not needed anymore.
But this is not work yet....

**Comment by cbeust** [comment]
@dmitry-zhuravlev But until this is done automatically, just specifying `kotlin-stdlib` and `kotlin-runtime` in your dependencies should work as well, right?

**Comment by dmitry-zhuravlev** [comment]
> just specifying kotlin-stdlib and kotlin-runtime in your dependencies should work as well, right?

Yep, this is what exactly what `as Kotlin (Kobalt) module` do. But also can be done manually simple by editing `Build.kt` `dependencies` section.

 FYI just created some PR to Kotlin plugin: https://github.com/JetBrains/kotlin/pull/1067
this will help to hide `as Kotlin (Java) module` and `as Kotlin (JavaScript) module`. It would be good if JB accept it and this will hide default configurators just to not confuse users.

**Comment by ethauvin** [comment]
@dmitry-zhuravlev As stated in https://github.com/cbeust/kobalt-intellij-plugin/issues/80#issuecomment-298042958, choosing `as Kotlin (Kobalt) module` does not work either. It does stop the looping but no longer finds Kobalt's own libraries.

**Comment by ethauvin** [comment]
Here it is in pictures:

![2017-05-02 09_26_49-kobalt-exec - k__kotlin_kobalt-exec - kobalt-exec - _src_main_kotlin_net_](https://cloud.githubusercontent.com/assets/705618/25628199/3879d5fa-2f1a-11e7-96fe-97bf5ffe826f.png)
![2017-05-02 09_27_06-configure kotlin in project](https://cloud.githubusercontent.com/assets/705618/25628201/3a07e36c-2f1a-11e7-895b-6b1acbc53f35.png)
![2017-05-02 09_27_56-kobalt-exec - k__kotlin_kobalt-exec - build kt - _kobalt_src_build kt - i](https://cloud.githubusercontent.com/assets/705618/25628204/3bfc4d48-2f1a-11e7-882a-c2097ea4f48e.png)
![2017-05-02 09_28_12-kobalt-exec - k__kotlin_kobalt-exec - build kt - _kobalt_src_build kt - i](https://cloud.githubusercontent.com/assets/705618/25628207/3dc9ba02-2f1a-11e7-82be-1d99ad7c1f4f.png)
![2017-05-02 09_29_50-kobalt-exec - k__kotlin_kobalt-exec - kobalt-exec - _src_main_kotlin_net_](https://cloud.githubusercontent.com/assets/705618/25628212/3fb81318-2f1a-11e7-93fe-9147085797ea.png)

Basically still unusable.

**Comment by dmitry-zhuravlev** [comment]
Hmm... But on the last screenshot I see that some classes from `com.beust.*` and `com.google.*` packages are not resolved. I guess that this should be from `compileOnly("com.beust:$kobaltDependency:")` dependency.
I tried to add ` compile("org.jetbrains.kotlin:kotlin-stdlib:1.1.2-2")` in `Build.kt` and all classes from the standard Kotlin lib resolved fine.

@cbeust did Kobalt server even send `compileOnly` dependencies to plugin?
@ethauvin can you try to change from `compileOnly` to `compile` and press "Import changes" on tooltip?

**Comment by ethauvin** [comment]
Yes, that fixed the issue. Makes no sense, `compileOnly` was implemented weeks ago, and there weren't any issues until I updated the Kotlin runtime.

**Comment by ethauvin** [comment]
@cbeust can you make sure that `compileOnly` deps are sent to the plugin? I'd do it, but I know nothing about the server portion of kobalt.

**Comment by cbeust** [comment]
Will do but you can already quickly check yourself:

```
./kobaltw --server --force --log 2
```

Then push the Sync button in IDE, the server should give you the list of dependencies it's sending to the IDE.
