### ISSUE TITLE
Getting `NotSerializableException` when importing a new project

### ISSUE THREAD

**Issue by cbeust** [cbeust/kobalt-intellij-plugin#86]
![image](https://user-images.githubusercontent.com/92322/33294538-f3a60d2a-d385-11e7-8e10-dc2bfd711794.png)

![image](https://user-images.githubusercontent.com/92322/33294563-1305fb8a-d386-11e7-9511-4f6e5891d9b0.png)

**Comment by cbeust** [comment]
```
/Users/cedricbeust/java/testng/kobalt/src/Build.kt
Error:Error unmarshaling return; nested exception is: 
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: com.intellij.execution.configurations.GeneralCommandLine
Kobalt 'testng' project refresh failed
Error:Error unmarshaling return; nested exception is: 
	java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: com.intellij.execution.configurations.GeneralCommandLine
writing aborted; java.io.NotSerializableException: com.intellij.execution.configurations.GeneralCommandLine
com.intellij.execution.configurations.GeneralCommandLine
```

**Comment by dmitry-zhuravlev** [comment]
Weird exception... Just tried to import "testng" project with latest Kobalt 1.0.92 and IDEA 2017.3 and it successfully imported:
![image](https://user-images.githubusercontent.com/6297697/33761582-a1e91c3c-dc1a-11e7-9b03-4634246e672a.png)

**Comment by cbeust** [comment]
It's working for me now, not sure what I did, though, but it did prevent me from importing anything for a while. Closing for now.
